### ISSUE TITLE
Remove Thread.Sleep from benchmark

### ISSUE THREAD

**Issue by snakefoot** [jakdaniel/NlogSerilogDotnetBenchmark#2]
Your benchmark is only testing the performance of `Thread.Sleep`:

https://github.com/jakdaniel/NlogSerilogDotnetBenchmark/blob/b1e501e031a9f4a7164fccc3c08e797ec96cbbb8/Logger/DoSomethingElse.cs#L26

**Comment by jakdaniel** [comment]
It's only to simulate some kind of work

**Comment by snakefoot** [comment]
It was only to explain your observation:

> Nlog or Serilog seems to have the same performance in terms of execution time

Look forward to updated benchmark-results, though you will only see NLog memory-allocation has dropped. If you continue to test the performance of `Thread.Sleep`.

**Comment by snakefoot** [comment]
@jakdaniel Any chance to have [README.md](https://github.com/jakdaniel/NlogSerilogDotnetBenchmark/blob/main/README.md) updated after the new improvements?
